import type { Metadata } from "next";
import { Inter, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const bricol = Bricolage_Grotesque({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EzResume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bricol.className}>{children}</body>
    </html>
  );
}
